module.exports = {
  apps: [
    {
      name: "ramazonbot-api-9999",
      script: "./bot.js",
      cwd: "/root/ramazonbot/api",
      instances: 1,
      exec_mode: "fork",
      env: {
        NODE_ENV: "production",
        TZ: "Asia/Tashkent",
        PORT: "9999",
      },
      error_file: "./logs/pm2-api-error.log",
      out_file: "./logs/pm2-api-out.log",
      log_date_format: "YYYY-MM-DD HH:mm:ss Z",
      merge_logs: true,
      max_memory_restart: "500M",
      restart_delay: 3000,
    },
    {
      name: "ramazonbot-cache-refresh",
      script: "./scripts/cache/cache-refresh-scheduler.js",
      cwd: "/root/ramazonbot/api",
      instances: 1,
      exec_mode: "fork",
      env: {
        NODE_ENV: "production",
        TZ: "Asia/Tashkent",
      },
      error_file: "./logs/cache-refresh-error.log",
      out_file: "./logs/cache-refresh-out.log",
      log_date_format: "YYYY-MM-DD HH:mm:ss Z",
      merge_logs: true,
      max_memory_restart: "200M",
      restart_delay: 5000,
    },
    {
      name: "ramazonbot-backup-scheduler",
      script: "./scripts/maintenance/backup-scheduler.js",
      cwd: "/root/ramazonbot/api",
      instances: 1,
      exec_mode: "fork",
      env: {
        NODE_ENV: "production",
        TZ: "Asia/Tashkent",
      },
      error_file: "./logs/backup-scheduler-error.log",
      out_file: "./logs/backup-scheduler-out.log",
      log_date_format: "YYYY-MM-DD HH:mm:ss Z",
      merge_logs: true,
      max_memory_restart: "200M",
      restart_delay: 5000,
    },
    {
      name: "ramazonbot-admin-9998",
      script: "./nginx/server.main.js",
      cwd: "/root/ramazonbot/admin-panel",
      instances: 1,
      exec_mode: "fork",
      env: {
        NODE_ENV: "production",
        PORT: "9998",
      },
      error_file: "./logs/pm2-admin-error.log",
      out_file: "./logs/pm2-admin-out.log",
      log_date_format: "YYYY-MM-DD HH:mm:ss Z",
      merge_logs: true,
      max_memory_restart: "300M",
      restart_delay: 3000,
    },
    {
      name: "ramazonbot-webapp-9997",
      script: "./nginx/server.main.js",
      cwd: "/root/ramazonbot/mini-app",
      instances: 1,
      exec_mode: "fork",
      env: {
        NODE_ENV: "production",
        PORT: "9997",
      },
      error_file: "./logs/pm2-webapp-error.log",
      out_file: "./logs/pm2-webapp-out.log",
      log_date_format: "YYYY-MM-DD HH:mm:ss Z",
      merge_logs: true,
      max_memory_restart: "300M",
      restart_delay: 3000,
    },
  ],
};
